import { v4 as uuidv4 } from "uuid";

/**
 * Phase 1 Agent Kernel:
 * - routes a user message to an agent key
 * - creates a "proposal" object (approval flow later)
 *
 * Later: this will call OpenAI + tools.
 */

export const DEFAULT_AGENTS = [
  { key: "orion", name: "Orion", description: "Strategy & planning agent" },
  { key: "nova", name: "Nova", description: "Instagram content agent" },
  { key: "atlas", name: "Atlas", description: "WhatsApp/Sales agent" },
  { key: "echo", name: "Echo", description: "Analytics agent" }
];

export async function ensureDefaultAgents(pool) {
  for (const a of DEFAULT_AGENTS) {
    await pool.query(
      `INSERT INTO agents (id, key, name, description)
       VALUES ($1,$2,$3,$4)
       ON CONFLICT (key) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description`,
      [uuidv4(), a.key, a.name, a.description || null]
    );
  }
}

export function routeToAgent(text) {
  const t = String(text || "").toLowerCase();

  // very simple routing rules (we’ll improve later)
  if (t.includes("instagram") || t.includes("post") || t.includes("reels") || t.includes("story")) return "nova";
  if (t.includes("whatsapp") || t.includes("satış") || t.includes("satis") || t.includes("qiymət") || t.includes("price"))
    return "atlas";
  if (t.includes("analiz") || t.includes("report") || t.includes("stat") || t.includes("metrics")) return "echo";
  return "orion";
}

/**
 * Creates a proposal (approval pipeline).
 * For now: always proposes "send_message" response.
 */
export function makeAssistantProposal({ conversationId, userText }) {
  const agentKey = routeToAgent(userText);

  // Stub response (later: generated by OpenAI)
  const reply =
    agentKey === "nova"
      ? "Instagram üçün 1 qısa plan hazırlayım: hədəfin nədir (satış, brend, lead)?"
      : agentKey === "atlas"
      ? "Satış üçün 1 sual: müştəri hansı xidməti istəyir (veb, AI agent, chatbot)?"
      : agentKey === "echo"
      ? "Analiz üçün: hansı perioda baxaq (günlük/həftəlik) və əsas KPI nədir?"
      : "Strategiya üçün: əsas məqsəd nədir və bu həftə hədəf nə olsun?";

  return {
    id: uuidv4(),
    conversationId,
    agentKey,
    type: "send_message",
    payload: {
      text: reply
    }
  };
}